version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: zmfvmfdocuquiz
      POSTGRES_PASSWORD: afdfJKa#faB
      POSTGRES_DB: docuquiz
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  pgdata:
