version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: zmfvmfdocuquiz
      POSTGRES_PASSWORD: "simplepass"
      POSTGRES_DB: docuquiz
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5435:5432"

volumes:
  pgdata:
